version: '3'
services:
  zookeeper:
    image: zookeeper:3.9.1
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: apache/kafka:3.7.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  item-sync-service:
    build:
      context: .
      dockerfile: ItemSyncService/Dockerfile
    container_name: item-sync-service
    ports:
      - "8080:8080"
      - "5000:5000"  # Remote debugging port
    depends_on:
      - kafka
    environment:
      - KafkaSettings__BootstrapServers=kafka:29092
      - KafkaSettings__GroupId=ewp-sf-item-group
      - KafkaSettings__Topics__ItemSync=item-sync-topic
      - KafkaSettings__Topics__ItemUpdates=item-updates-topic
      - KafkaSettings__Consumer__MaxRetries=5
      - KafkaSettings__Consumer__InitialRetryDelayMs=2000
      - KafkaSettings__Consumer__AutoCreateTopics=true
      - ENABLE_REMOTE_DEBUG=true
      - VSTEST_HOST_DEBUG=1
      # Add this to make debugging more reliable
      - ASPNETCORE_ENVIRONMENT=Development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge





